name: strudel_dart
description: Dart port of Strudel core logic.
version: 1.0.0
homepage: https://strudel.cc/
repository: https://github.com/JAICHANGPARK/fstrudel

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  fraction: ^5.0.5
  petitparser: ^7.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
